/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TradeImport } from './routes/trade'
import { Route as SignupImport } from './routes/signup'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as PoolImport } from './routes/pool'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as ChangePasswordImport } from './routes/change-password'
import { Route as IndexImport } from './routes/index'
import { Route as AdminPositionsImport } from './routes/admin/positions'
import { Route as AdminPoolsImport } from './routes/admin/pools'
import { Route as AdminDashboardImport } from './routes/admin/dashboard'

// Create/Update Routes

const TradeRoute = TradeImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const PoolRoute = PoolImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const ChangePasswordRoute = ChangePasswordImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminPositionsRoute = AdminPositionsImport.update({
  id: '/admin/positions',
  path: '/admin/positions',
  getParentRoute: () => rootRoute,
} as any)

const AdminPoolsRoute = AdminPoolsImport.update({
  id: '/admin/pools',
  path: '/admin/pools',
  getParentRoute: () => rootRoute,
} as any)

const AdminDashboardRoute = AdminDashboardImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/pool': {
      id: '/pool'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof PoolImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeImport
      parentRoute: typeof rootRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardImport
      parentRoute: typeof rootRoute
    }
    '/admin/pools': {
      id: '/admin/pools'
      path: '/admin/pools'
      fullPath: '/admin/pools'
      preLoaderRoute: typeof AdminPoolsImport
      parentRoute: typeof rootRoute
    }
    '/admin/positions': {
      id: '/admin/positions'
      path: '/admin/positions'
      fullPath: '/admin/positions'
      preLoaderRoute: typeof AdminPositionsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pool': typeof PoolRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/trade': typeof TradeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pools': typeof AdminPoolsRoute
  '/admin/positions': typeof AdminPositionsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pool': typeof PoolRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/trade': typeof TradeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pools': typeof AdminPoolsRoute
  '/admin/positions': typeof AdminPositionsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pool': typeof PoolRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/trade': typeof TradeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pools': typeof AdminPoolsRoute
  '/admin/positions': typeof AdminPositionsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/login'
    | '/pool'
    | '/reset-password'
    | '/sign-up'
    | '/signup'
    | '/trade'
    | '/admin/dashboard'
    | '/admin/pools'
    | '/admin/positions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/login'
    | '/pool'
    | '/reset-password'
    | '/sign-up'
    | '/signup'
    | '/trade'
    | '/admin/dashboard'
    | '/admin/pools'
    | '/admin/positions'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/login'
    | '/pool'
    | '/reset-password'
    | '/sign-up'
    | '/signup'
    | '/trade'
    | '/admin/dashboard'
    | '/admin/pools'
    | '/admin/positions'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PoolRoute: typeof PoolRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignUpRoute: typeof SignUpRoute
  SignupRoute: typeof SignupRoute
  TradeRoute: typeof TradeRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPoolsRoute: typeof AdminPoolsRoute
  AdminPositionsRoute: typeof AdminPositionsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PoolRoute: PoolRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignUpRoute: SignUpRoute,
  SignupRoute: SignupRoute,
  TradeRoute: TradeRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPoolsRoute: AdminPoolsRoute,
  AdminPositionsRoute: AdminPositionsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/change-password",
        "/dashboard",
        "/login",
        "/pool",
        "/reset-password",
        "/sign-up",
        "/signup",
        "/trade",
        "/admin/dashboard",
        "/admin/pools",
        "/admin/positions"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/change-password": {
      "filePath": "change-password.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/pool": {
      "filePath": "pool.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/trade": {
      "filePath": "trade.tsx"
    },
    "/admin/dashboard": {
      "filePath": "admin/dashboard.tsx"
    },
    "/admin/pools": {
      "filePath": "admin/pools.tsx"
    },
    "/admin/positions": {
      "filePath": "admin/positions.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
