name: Pylint

on:
  push:
    branches: [main]
    paths:
      - "**/*.py"
  pull_request:
    branches: [main]
    paths:
      - "**/*.py"

jobs:
  shared:
    uses: ./.github/workflows/shared_workflow.yml
    with:
      python-version: "3.12"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          files=$(git ls-files '*.py')
          if [ -n "$files" ]; then
            pylint $files --disable=all --enable=C0114,C0115,C0116,C0301,C0103,W0611,W0612,W0613,W0621,C0411,C0413,E0401,E1101,W0102,W0212,R0913,R0914 || true
          else
            echo "No Python files found for linting."
          fi
